# Generated by Django 3.0 on 2020-05-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translatable_content', '0004_auto_20200506_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
