# Generated by Django 3.0.3 on 2020-05-10 01:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('translatable_content', '0005_auto_20200506_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='translatable_content.Post'),
        ),
        migrations.AlterField(
            model_name='content',
            name='value',
            field=tinymce.models.HTMLField(),
        ),
    ]
