# Generated by Django 3.0.3 on 2020-05-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translatable_content', '0006_auto_20200510_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='key',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='content',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='translatable_content.Media'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='translatable_content.Tag'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
