# Generated by Django 3.0 on 2020-05-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translatable_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='media',
            field=models.ManyToManyField(to='translatable_content.Media'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='tags',
            field=models.ManyToManyField(to='translatable_content.Tag'),
        ),
    ]
