# Generated by Django 3.0 on 2020-05-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translatable_content', '0003_auto_20200506_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
